#  Copyright (c) 2018-TODAY Open-Net Ltd. All rights reserved.
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
{
	'name': 'Open Net Productivity: Demo',
	'version': '1.0',
	'author': 'Open Net Sàrl',
	'category': 'Demo',
	'website': 'http://www.open-net.ch',
	'images': [],
	'depends': [
		'ons_productivity_accounting',
		'ons_productivity_accounting_bvr',
		'l10n_ch',
		'crm',
		'project',
		'stock',
		'mrp',
		'sale_management',
		'point_of_sale',
		'hr_timesheet',
		'mail',
		'hr_holidays',
		'account_invoicing',
		'hr_appraisal',
		'account_accountant',
		'note',
		'mrp_plm',
		'quality',
		'website',
		'website_sale',
		'helpdesk',
		'purchase',
		'hr',
		'hr_attendance',
		'hr_recruitment',
		'hr_expense',
		'board',
		'contacts',
		'marketing_automation',
		'project_forecast',
		'sale_subscription',
		'stock_barcode',
		'voip',
		'website_sign',
		'web_studio',
		'survey',
		'mass_mailing',
		'calendar',
		'website_calendar',
		'website_blog',
		'website_slides',
		'website_forum',
		'fleet',
		'website_event',
		'mrp_repair',
		'link_tracker',
	],
	'data': [
		'views/website_views.xml',
		'views/products_views.xml'
	],
	'js': [
	],
	'qweb' : [
	],
	'css':[
	],
	'demo': [
	],
	'test': [
	],
	'installable': True,
	'auto_install': False,
}